version: "3.8"

services:
  typesense:
    image: typesense/typesense:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:35506:8108"
    volumes:
      - ./typesense-data:/data
    command: 
      - --data-dir 
      - /data
      - --api-key=${TYPESENSE_API_KEY} 
      - --enable-cors
      - --enable-access-logging
