version: "3.8"

services:
  typesense:
    image: typesense/typesense:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:8108:8108"
    volumes:
      - ./typesense_data:/data
    env_file:
      - .env
    command: 
      - --enable-access-logging
